# (C) Copyright 2017 o2r project. https://o2r.info
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
---
version: '2'

volumes:
  o2rvol: {}

services:
  mongodb:
    image: mongo:3.6
    command: "--replSet rso2r"

  configmongodb:
    image: mongo:3.6
    depends_on:
      - mongodb
    command: bash -c "sleep 5; mongo --verbose --host mongodb --eval 'printjson(rs.initiate()); printjson(rs.conf()); printjson(rs.status()); printjson(rs.slaveOk());'"

  mongoadmin:
    image: adicom/admin-mongo:latest
    depends_on:
      - mongodb
    environment:
      - DB_HOST=mongodb
      - CONN_NAME=Local 
    ports:
      - "1234:1234"

  meta:
    image: o2r_refimpl_meta
    build:
      context: o2r-meta

  containerit:
    image: o2r_refimpl_containerit
    build:
      context: containerit
      dockerfile: inst/docker/geospatial/Dockerfile.local

  muncher:
    image: o2r_refimpl_muncher
    build:
      context: ./o2r-muncher
    depends_on:
      - configmongodb
    volumes:
      - o2rvol:/tmp/o2r
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "MUNCHER_MONGODB=mongodb://mongodb:27017/"
      - MUNCHER_PORT=8080
      - MUNCHER_VOLUME=referenceimplementation_o2rvol
      - MUNCHER_CONTAINER_USER=root
      - MUNCHER_CONTAINERIT_USER=root
      - MUNCHER_CONTAINERIT_IMAGE=o2r_refimpl_containerit
      - DEBUG=*,-mquery,-express:*,-express-session,-body-parser:*
      - "MUNCHER_META_TOOL_CONTAINER=o2r_refimpl_meta"

  bouncer:
    image: o2r_refimpl_bouncer
    build:
      context: ./o2r-bouncer
    depends_on:
      - configmongodb
    environment:
      - "BOUNCER_MONGODB=mongodb://mongodb:27017/"
      - BOUNCER_PORT=8083
      - DEBUG=bouncer
      - OAUTH_URL_CALLBACK=${OAUTH_URL_CALLBACK}
      - OAUTH_URL_AUTHORIZATION=${OAUTH_URL_AUTHORIZATION}
      - OAUTH_URL_TOKEN=${OAUTH_URL_TOKEN}
      - OAUTH_STARTUP_FAIL_ON_ERROR=false

  shipper:
    image: o2r_refimpl_shipper
    build:
      context: ./o2r-shipper
    depends_on:
      - configmongodb
    volumes:
      - o2rvol:/tmp/o2r
    environment:
      SHIPPER_MONGODB: "mongodb://mongodb"
      SHIPPER_REPO_TOKENS: "${SHIPPER_REPO_TOKENS}"
      SHIPPER_BOTTLE_HOST: "0.0.0.0"
      SHIPPER_BASE_PATH: "/tmp/o2r"
      PYTHONUNBUFFERED: "0"

  bindings:
    image: o2r_refimpl_bindings
    build:
      context: ./o2r-ui/ui/bindings
    volumes:
      - o2rvol:/tmp/o2r
    environment: 
      - DEBUG=bindings

  guestlister:
    image: o2r_refimpl_guestlister
    build:
      context: ./o2r-guestlister
    depends_on:
      - configmongodb
    environment:
      - "GUESTLISTER_MONGODB=mongodb://mongodb:27017/"
      - GUESTLISTER_PORT=8383
      - DEBUG=guestlister
      - OAUTH_URL_CALLBACK=${OAUTH_URL_CALLBACK}
      - OAUTH_URL_AUTHORIZATION=${OAUTH_URL_AUTHORIZATION}
      - OAUTH_URL_TOKEN=${OAUTH_URL_TOKEN}

  ui:
    image: o2r_refimpl_ui
    build:
      context: ./o2r-ui/ui
    restart: unless-stopped

  webserver:
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      - bouncer
      - muncher
      - shipper
    ports:
      - "80:80"

